title: KD Pixels
email: dev@kdpixels.com
author: Kshitij Deota
description: >- # this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog

url: "https://kdpixels.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kshitijdeota
github_username: kshitijdeota

# Build settings
markdown: kramdown
permalink: pretty
theme: null
show_drafts: false

sass:
  sass_dir: assets/css
  style: :nested

plugins:
  - jekyll-feed
  - paginate: 5
